using CodePulse.API.Data;
using CodePulse.API.Models.Domain;
using CodePulse.API.Models.DTO;
using Microsoft.AspNetCore.Mvc;

namespace CodePulse.API.Controllers{
  // https://localhost:xxxx/api/categories
  [Route("api/[controller]")]
  [ApiController]
  public class CategoriesController : ControllerBase
  {
    private readonly ApplicationDbContext dbContext;
    public CategoriesController(ApplicationDbContext dbContext)
    {
      this.dbContext = dbContext;
    }

    //
    [HttpPost]
    public async Task<IActionResult> CreateCategory(CreateCategoryRequestDto request)
    {
      // Map DTO to Domain Model，id will generated by database
      var category = new Category{
        Name = request.Name,
        UrlHandle = request.UrlHandle   
      };

      await dbContext.Categories.AddAsync(category);
      await dbContext.SaveChangesAsync();


    // Map Domain Model to DTO, return the generated id
      var response = new CategoryDTO{
        Id = category.Id,
        Name = category.Name,
        UrlHandle = category.UrlHandle
      };

      return Ok(response);
    }
  }
}